site_name: My Docs

theme:
  name: "material"
  palette:
    # Definir o tema escuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      media: "(prefers-color-scheme: dark)"

plugins:
  - search
  - mkdocstrings:
      default_handler: python